stages:

  # evaluate:
  #   cmd: python evaluate.py --model-path models/best_model.pth --test-dir data/processed/test
  #   deps:
  #     - scripts/evaluate.py
  #     - models/best_model.pth
  #     - data/processed/test
  #   metrics:
  #     - eval/metrics.json:
  #         cache: false

  api_deployment:
    cmd: cmd /c "start /b python prediction.py && python -m http.server 8080"
    deps:
      - prediction.py
      - models/best_model.pth
      - util_classes.py
      - util_model_classes.py
      - utils_test.py
      - index.html