stages:
  # Check feedback data and trigger retraining if necessary
  feedback_check:
    cmd: python check_feedback.py --feedback-dir feedback_data --threshold 100
    deps:
      - feedback_data
      - check_feedback.py
    outs:
      - feedback_check_done.txt

  # Retraining stage (only runs if feedback exceeds threshold)
  retraining:
    cmd: python train.py --train-data retraining_data --save-model-path models/best_model_retrained.pth
    deps:
      - retraining_data
      - check_feedback.py
    outs:
      - models/best_model_retrained.pth

  update_model:
    cmd: python -c "import shutil; shutil.copy('models/best_model_retrained.pth', 'models/best_model.pth')"
    deps:
      - models/best_model_retrained.pth

  # Deployment stage (always runs after retraining or manually)
  api_deployment:
    cmd: cmd /c "start /b python prediction.py && python -m http.server 8091"
    deps:
      - prediction.py
      - check_feedback.py
      - models/best_model.pth
      - utils/util_classes.py
      - utils/util_model_classes.py
      - utils/utils_test.py
      - index.html
